language: c++
dist: xenial

addons:
  apt:
    packages:
      - libcppunit-dev
      - cmake

compiler:
  - clang
  - gcc

env:
  - CONF="-DUSE_TAGGING=true  -DGC_TYPE=GENERATIONAL"
  - CONF="-DUSE_TAGGING=true  -DGC_TYPE=MARK_SWEEP"
  - CONF="-DUSE_TAGGING=true  -DGC_TYPE=COPYING"
  
  - CONF="-DUSE_TAGGING=false -DGC_TYPE=GENERATIONAL -DCACHE_INTEGER=true"
  - CONF="-DUSE_TAGGING=false -DGC_TYPE=MARK_SWEEP   -DCACHE_INTEGER=true"
  - CONF="-DUSE_TAGGING=false -DGC_TYPE=COPYING      -DCACHE_INTEGER=true"
  
  - CONF="-DUSE_TAGGING=false -DGC_TYPE=GENERATIONAL -DCACHE_INTEGER=false"
  - CONF="-DUSE_TAGGING=false -DGC_TYPE=MARK_SWEEP   -DCACHE_INTEGER=false"
  - CONF="-DUSE_TAGGING=false -DGC_TYPE=COPYING      -DCACHE_INTEGER=false"

script:
    - cmake . $CONF
    - make
    - ./SOM++ -cp ./Smalltalk ./TestSuite/TestHarness.som
    - ./SOM++ -cp ./Smalltalk:./Examples/Benchmarks/LanguageFeatures ./Examples/Benchmarks/All.som
    - ./unittests -cp ./Smalltalk ./Examples/Hello.som
